AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA0002) - sagemaker-graph-fraud-detection SageMaker permissions stack"
Parameters:
  SolutionS3BucketName:
    Description: Enter the name of the S3 bucket for the solution
    Type: String

Mappings:
  S3:
    SolutionRef:
      Bucket: "sagemaker-solutions"
      
Resources:
  NotebookInstanceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
            - 'sts:AssumeRole'
  NotebookInstanceIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: graph-fraud-detection-notebook-instance-policy
      Roles:
        - !Ref NotebookInstanceExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sagemaker:CreateTrainingJob
          - sagemaker:DescribeTrainingJob
          - sagemaker:CreateProcessingJob
          - sagemaker:DescribeProcessingJob
          Resource:
          - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
          - ecr:GetAuthorizationToken
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:PutImage
          - ecr:BatchCheckLayerAvailability
          - ecr:CreateRepository
          - ecr:DescribeRepositories
          - ecr:InitiateLayerUpload
          - ecr:CompleteLayerUpload
          - ecr:UploadLayerPart
          - ecr:TagResource
          Resource:
          - "*"
          - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"
        - Effect: Allow
          Action:
          - cloudwatch:PutMetricData
          - cloudwatch:GetMetricData
          - cloudwatch:GetMetricStatistics
          - cloudwatch:ListMetrics
          Resource:
          - !Sub "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogStreams
          - logs:GetLogEvents
          - logs:PutLogEvents
          Resource:
          - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/sagemaker/*"
        - Effect: Allow
          Action:
          - iam:PassRole
          Resource:
          - !GetAtt NotebookInstanceExecutionRole.Arn
          Condition:
            StringEquals:
              iam:PassedToService: sagemaker.amazonaws.com
        - Effect: Allow
          Action:
          - iam:GetRole
          Resource:
          - !GetAtt NotebookInstanceExecutionRole.Arn
        - Effect: Allow
          Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          Resource:
          - !Sub "arn:aws:s3:::${SolutionS3BucketName}"
          - !Sub "arn:aws:s3:::${SolutionS3BucketName}/*"
          - !Sub
            - "arn:aws:s3:::${SolutionRefBucketBase}-${Region}"
            - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
              Region: !Ref AWS::Region
          - !Sub
            - "arn:aws:s3:::${SolutionRefBucketBase}-${Region}/*"
            - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
              Region: !Ref AWS::Region
        - Effect: Allow
          Action:
          - s3:CreateBucket
          - s3:ListBucket
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          Resource:
          - !Sub "arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}"
          - !Sub "arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}/*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: ECR GetAuthorizationToken is non resource-specific action

Outputs:
  SageMakerRoleArn:
    Description: "SageMaker Execution Role for the solution"
    Value: !GetAtt NotebookInstanceExecutionRole.Arn