AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA0002) - sagemaker-graph-fraud-detection: Solution for training a graph neural network model for fraud detection using Amazon SageMaker. Version 1"
Parameters:
  SolutionS3BucketPrefix:
    Description: Enter the base name of the S3 bucket for the solution
    Type: String
    Default: "sagemaker-graph-fraud-detection"
  S3HistoricalTransactionsPrefix:
    Description: Enter the S3 prefix where historical transactions/relations are stored.
    Type: String
    Default: "raw-data"
  S3ProcessingJobInputPrefix:
    Description: Enter the S3 prefix where inputs should be monitored for changes to start the processing job
    Type: String
    Default: "processing-input"
  S3ProcessingJobOutputPrefix:
    Description: Enter the S3 prefix where preprocessed data should be stored and monitored for changes to start the training job
    Type: String
    Default: "preprocessed-data"
  S3TrainingJobOutputPrefix:
    Description: Enter the S3 prefix where model and output artifacts from the training job should be stored
    Type: String
    Default: "training-output"
  LaunchSageMakerNotebookClassic:
    Description: Whether to launch classic sagemaker notebook instance
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"
  SageMakerProcessingJobContainerName:
    Description: Name of the SageMaker processing job ECR Container
    Type: String
    Default:  "sagemaker-preprocessing-container"
  SageMakerProcessingJobInstanceType:
    Description: Instance type of the SageMaker processing job
    Type: String
    Default:  "ml.m4.xlarge"
  SageMakerTrainingJobInstanceType:
    Description: Instance type of the SageMaker processing job
    Type: String
    Default:  "ml.p3.2xlarge"
  SageMakerNotebookInstanceType:
    Description: Instance type of the SageMaker notebook instance
    Type: String
    Default:  "ml.t3.medium"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: S3 Configuration
        Parameters:
          - SolutionS3BucketPrefix
          - S3HistoricalTransactionsPrefix
          - S3ProcessingJobInputPrefix
          - S3ProcessingJobOutputPrefix
          - S3TrainingJobOutputPrefix
      -
        Label:
          default: SageMaker Configuration
        Parameters:
          - LaunchSageMakerNotebookClassic
          - SageMakerProcessingJobContainerName
          - SageMakerProcessingJobInstanceType
          - SageMakerTrainingJobInstanceType
          - SageMakerNotebookInstanceType
    ParameterLabels:
      SolutionS3BucketPrefix:
        default: S3 Bucket Prefix
      S3HistoricalTransactionsPrefix:
        default: S3 Data Prefix
      S3ProcessingJobInputPrefix:
        default: S3 Processing Input Prefix
      S3ProcessingJobOutputPrefix:
        default: S3 Preprocessed Data Prefix
      S3TrainingJobOutputPrefix:
        default: S3 Training Results Prefix
      LaunchSageMakerNotebookClassic:
        default: Launch Classic SageMaker Notebook Instance
      SageMakerProcessingJobContainerName:
        default: SageMaker Processing Container Name
      SageMakerProcessingJobInstanceType:
        default: SageMaker Processing Instance
      SageMakerTrainingJobInstanceType:
        default: SageMaker Training Instance
      SageMakerNotebookInstanceType:
        default: SageMaker Notebook Instance

Mappings:
  S3:
    SolutionRef:
      Bucket: "sagemaker-solutions"
  Lambda:
    DataPreprocessing:
      S3Key: "Fraud-detection-in-financial-networks/build/data_preprocessing.zip"
    GraphModelling:
      S3Key: "Fraud-detection-in-financial-networks/build/graph_modelling.zip"

Conditions:
  CreateClassicSageMakerResources: !Equals [ !Ref LaunchSageMakerNotebookClassic, "Yes" ]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event: s3:ObjectCreated:*
            Function: !GetAtt DataPreprocessingLambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref S3ProcessingJobInputPrefix
          -
            Event: s3:ObjectCreated:*
            Function: !GetAtt GraphModellingLambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref S3ProcessingJobOutputPrefix
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: Configuring logging requires supplying an existing customer S3 bucket to store logs
          - id: W51
            reason: Default access policy suffices
  
  SageMakerPermissionsStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
      - "https://s3.amazonaws.com/${SolutionRefBucketBase}-${Region}/Fraud-detection-in-financial-networks/deployment/sagemaker-permissions-stack.yaml"
      - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
        Region: !Ref AWS::Region
      Parameters:
        SolutionS3BucketName: !Sub "${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"

  SageMakerStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateClassicSageMakerResources
    Properties:
      TemplateURL: !Sub
      - "https://s3.amazonaws.com/${SolutionRefBucketBase}-${Region}/Fraud-detection-in-financial-networks/deployment/sagemaker-notebook-instance-stack.yaml"
      - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
        Region: !Ref AWS::Region
      Parameters:
        SolutionS3BucketName: !Sub "${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
        SageMakerProcessingJobInstanceType: !Ref SageMakerProcessingJobInstanceType
        SageMakerTrainingJobInstanceType: !Ref SageMakerTrainingJobInstanceType
        SageMakerNotebookInstanceType: !Ref SageMakerNotebookInstanceType
        NotebookInstanceExecutionRoleArn: !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: InvokeSagemaker
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - sagemaker:CreateTrainingJob
              - sagemaker:DescribeTrainingJob
              - sagemaker:CreateProcessingJob
              - sagemaker:DescribeProcessingJob
              Resource:
              - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*"
        -
          PolicyName: ReadWriteFromS3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
              - !Sub "arn:aws:s3:::${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}/*"
  DataPreprocessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "index.process_event"
      FunctionName: "sagemaker-graph-fraud-data-preprocessing"
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          processing_job_ecr_repository: !Ref SageMakerProcessingJobContainerName
          processing_job_input_s3_prefix: !Ref S3ProcessingJobInputPrefix
          processing_job_instance_type: !Ref SageMakerProcessingJobInstanceType
          processing_job_output_s3_prefix: !Ref S3ProcessingJobOutputPrefix
          processing_job_role_arn: !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn
          processing_job_s3_bucket: !Sub "${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
          processing_job_s3_raw_data_key: !Ref S3HistoricalTransactionsPrefix
      Runtime: "python3.7"
      Code:
        S3Bucket: !Sub
          - "${SolutionRefBucketBase}-${Region}"
          - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
            Region: !Ref AWS::Region
        S3Key: !FindInMap [Lambda, DataPreprocessing, S3Key]
      Timeout : 60
      MemorySize : 256
  DataPreprocessingLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DataPreprocessingLambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
      SourceAccount: !Ref AWS::AccountId
  GraphModellingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "index.process_event"
      FunctionName: "sagemaker-graph-fraud-model-training"
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          training_job_instance_type: !Ref SageMakerTrainingJobInstanceType
          training_job_output_s3_prefix: !Ref S3TrainingJobOutputPrefix
          training_job_role_arn: !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn
          training_job_s3_bucket: !Sub "${SolutionS3BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
      Runtime: "python3.7"
      Code:
        S3Bucket: !Sub
          - "${SolutionRefBucketBase}-${Region}"
          - SolutionRefBucketBase: !FindInMap [S3, SolutionRef, Bucket]
            Region: !Ref AWS::Region
        S3Key: !FindInMap [Lambda, GraphModelling, S3Key]
      Timeout : 60
      MemorySize : 256
  GraphModellingLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref GraphModellingLambda
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

Outputs:
  SourceCode:
    Condition: CreateClassicSageMakerResources
    Description: "Open Jupyter IDE. This authenticate you against Jupyter."
    Value: !GetAtt SageMakerStack.Outputs.SourceCode

  NotebookInstance: 
    Condition: CreateClassicSageMakerResources
    Description: "SageMaker Notebook instance to manually orchestrate data preprocessing and model training"
    Value: !GetAtt SageMakerStack.Outputs.NotebookInstance
